services:
  - name: ar-guideline-app
    type: web
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/ar-guideline-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        fromDatabase: ar-capstone-db
      - key: DB_USERNAME
        fromDatabase: ar-capstone-db
      - key: DB_PASSWORD
        fromDatabase: ar-capstone-db
      - key: REDIS_HOST
        value: singapore-redis.render.com
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        value: xT7peIJhFvZtpceqMzgrhpr5kECAvGfa
      - key: REDIS_SSL
        value: "true"
    plan: starter
    region: singapore
    healthCheckPath: /
    autoDeploy: true
    disk:
      sizeGB: 5
      mountPath: /data

databases:
  - name: ar-capstone-db
    plan: starter
    region: singapore
    diskSizeGB: 5
