services:
  - name: ar-guideline-app
    type: web
    runtime: java17  # Use java17 instead of java21
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/ar-guideline-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        fromDatabase:
          name: ar-capstone-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: ar-capstone-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ar-capstone-db
          property: password
      - key: REDIS_HOST
        value: singapore-redis.render.com
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        value: xT7peIJhFvZtpceqMzgrhpr5kECAvGfa
      - key: REDIS_SSL
        value: "true"
    plan: starter
    region: singapore
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: ar-guideline-app-disk  # Ensure a valid disk name
      sizeGB: 5
      mountPath: /data

databases:
  - name: ar-capstone-db
    plan: starter
    region: singapore
    diskSizeGB: 5
    databaseName: ar_capstone
    user: sa
