name: CI/CD - Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Chạy khi bạn push vào nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout source code
      uses: actions/checkout@v3

    - name: 🔐 Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: 🐳 Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ar-guideline:latest .

    - name: ☁️ Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ar-guideline:latest
